---
development:
    # Infrastructure
    API_HOST: http://localhost:9090

test:
    # Infrastructure
    API_HOST: http://localhost:9090

app_test:
    # Application
    APP_HOST: http://localhost:9292
    API_HOST: http://localhost:9090

production:
    # Infrastructure
    API_HOST: https://api-youtube-comment-filter.herokuapp.com
