---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  APP_HOST: http://localhost:9000

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  APP_HOST: http://localhost:9000
